<!DOCTYPE html>
<html>
<head>

<meta charset="UTF-8">
<title>Sistema de Exercícios PHP</title>
<link rel="stylesheet" href="style.css">

</head>

<body>

<div class="container">

<h1>Desafio 4 - Formulários PHP</h1>

<h2>Sequenciais</h2>

<div class="grid">
<a class="card" href="exer1.php">Conversor de Moedas</a>
<a class="card" href="exer2.php">Área e Perímetro</a>
<a class="card" href="exer3.php">Consumo Combustível</a>
</div>

<h2>IF / SWITCH</h2>

<div class="grid">
<a class="card" href="exer4.php">Situação do Aluno</a>
<a class="card" href="exer5.php">Verificador de Idade</a>
<a class="card" href="exer6.php">Par ou Ímpar</a>
<a class="card" href="exer7.php">Dias da Semana</a>
<a class="card" href="exer8.php">Calculadora</a>
<a class="card" href="exer9.php">Mês por Extenso</a>
</div>

<h2>Laços de Repetição</h2>

<div class="grid">
<a class="card" href="exer10.php">Fatorial</a>
<a class="card" href="exer11.php">Somatório</a>
<a class="card" href="exer12.php">Sequência Pares</a>
</div>

<h2>Arrays</h2>

<div class="grid">
<a class="card" href="exer13.php">Média Valores</a>
<a class="card" href="exer14.php">Lista Compras</a>
<a class="card" href="exer15.php">Maior e Menor</a>
</div>

</div>

</body>
</html>